title: Ica Skinned Mesh Docs
description: Documentation for the Unity Asset Ica Skinned Mesh.
theme: just-the-docs

url: https://ica-software.github.io

aux_links:
  Forum Page: https://discussions.unity.com/t/ica-skinned-mesh-better-than-skinned-mesh-renderer-dual-quaternion-skinning-and-much-more/1581924
  Sample: https://ica-dev.itch.io/ica-skinned-mesh-renderer-sample

logo: "/assets/images/IcaSMR_icon.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon/favicon.ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
